[actions]
build = "scripts/build.sh"
clean = "scripts/clean.sh"
lint = "scripts/lint.sh"
run = "scripts/run.sh"
watch = "scripts/run.sh"

[dependencies.git.hump]
path = "vendor/hump"
version = "https://github.com/vrld/hump.git"

[devDependencies.luarocks]
luasocket = "*"
