[actions]
build = "build/build.sh"
clean = "build/clean.sh"
run = "build/run.sh"
watch = "build/run.sh"

[dependencies.git.hump]
path = "vendor/hump"
version = "https://github.com/vrld/hump.git"

[devDependencies.luarocks]
luasocket = "*"
